package com.p5k.simple_rv.common;

import com.p5k.simple_rv.model.Champ;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Constant {
    public static Champ Aatrox = new Champ("Aatrox", 1, 1);
    public static Champ Aphelios = new Champ("Aphelios", 3, 2);
    public static Champ Ashe = new Champ("Ashe", 3, 3);
    public static Champ Brand = new Champ("Brand", 2, 4);
    public static Champ Darius = new Champ("Darius", 5, 5);
    public static Champ Diana = new Champ("Diana", 4, 6);
    public static Champ Draven = new Champ("Draven", 4, 7);
    public static Champ Garen = new Champ("Garen", 4, 8);
    public static Champ Gragas = new Champ("Gragas", 1, 9);
    public static Champ Hecarim = new Champ("Hecarim", 2, 10);
    public static Champ Heimerdinger = new Champ("Heimerdinger", 5, 11);
    public static Champ Ivern = new Champ("Ivern", 4, 12);
    public static Champ Jax = new Champ("Jax", 4, 13);
    public static Champ Kalista = new Champ("Kalista", 1, 14);
    public static Champ Karma = new Champ("Karma", 4, 15);
    public static Champ Katarina = new Champ("Katarina", 3, 16);
    public static Champ Kayle = new Champ("Kayle", 5, 17);
    public static Champ Kennen = new Champ("Kennen", 2, 18);
    public static Champ Khazix = new Champ("Khazix", 1, 19);
    public static Champ Kindred = new Champ("Kindred", 5, 20);
    public static Champ Kled = new Champ("Kled", 1, 21);
    public static Champ LeBlanc = new Champ("LeBlanc", 2, 22);
    public static Champ Leona = new Champ("Leona", 4, 23);
    public static Champ Lissandra = new Champ("Lissandra", 1, 24);
    public static Champ Lulu = new Champ("Lulu", 3, 25);
    public static Champ Lux = new Champ("Lux", 3, 26);
    public static Champ Mordekaiser = new Champ("Mordekaiser", 4, 27);
    public static Champ Morgana = new Champ("Morgana", 3, 28);
    public static Champ Nautilus = new Champ("Nautilus", 2, 29);
    public static Champ Nidalee = new Champ("Nidalee", 3, 30);
    public static Champ Nocturne = new Champ("Nocturne", 3, 31);
    public static Champ Nunu = new Champ("Nunu", 3, 32);
    public static Champ Pantheon = new Champ("Pantheon", 3, 33);
    public static Champ Poppy = new Champ("Poppy", 1, 34);
    public static Champ Rell = new Champ("Rell", 4, 35);
    public static Champ Riven = new Champ("Riven", 3, 36);
    public static Champ Ryze = new Champ("Ryze", 4, 37);
    public static Champ Sejuani = new Champ("Sejuani", 2, 38);
    public static Champ Sett = new Champ("Sett", 2, 39);
    public static Champ Soraka = new Champ("Soraka", 2, 40);
    public static Champ Syndra = new Champ("Syndra", 2, 41);
    public static Champ Taric = new Champ("Taric", 4, 42);
    public static Champ Teemo = new Champ("Teemo", 5, 43);
    public static Champ Thresh = new Champ("Thresh", 2, 44);
    public static Champ Trundle = new Champ("Trundle", 2, 45);
    public static Champ Udyr = new Champ("Udyr", 1, 46);
    public static Champ Varus = new Champ("Varus", 2, 47);
    public static Champ Vayne = new Champ("Vayne", 1, 48);
    public static Champ VelKoz = new Champ("Vel'Koz", 4, 49);
    public static Champ Viego = new Champ("Viego", 5, 50);
    public static Champ Viktor = new Champ("Viktor", 2, 51);
    public static Champ Vladimir = new Champ("Vladimir", 1, 52);
    public static Champ Volibear = new Champ("Volibear", 5, 53);
    public static Champ Warwick = new Champ("Warwick", 1, 54);
    public static Champ Yasuo = new Champ("Yasuo", 3, 55);
    public static Champ Ziggs = new Champ("Ziggs", 1, 56);
    public static Champ Zyra = new Champ("Zyra", 3, 57);
    public static Champ LeeSin = new Champ("Lee Sin", 3, 57);

    private static final ArrayList<Champ> list = new ArrayList<>();

    public static List<Champ> getAllChamp() {
        list.add(Aatrox);
        list.add(Aphelios);
        list.add(Ashe);
        list.add(Brand);
        list.add(Diana);
        list.add(Darius);
        list.add(Draven);
        list.add(Garen);
        list.add(Gragas);
        list.add(Hecarim);
        list.add(Heimerdinger);
        list.add(Ivern);
        list.add(Jax);
        list.add(Kalista);
        list.add(Kayle);
        list.add(Katarina);
        list.add(Karma);
        list.add(Kennen);
        list.add(Khazix);
        list.add(Kindred);
        list.add(Kled);
        list.add(LeBlanc);
        list.add(LeeSin);
        list.add(Leona);
        list.add(Lissandra);
        list.add(Lulu);
        list.add(Lux);
        list.add(Mordekaiser);
        list.add(Morgana);
        list.add(Nocturne);
        list.add(Nidalee);
        list.add(Zyra);
        list.add(Ziggs);
        list.add(Yasuo);
        list.add(Warwick);
        list.add(Volibear);
        list.add(Vladimir);
        list.add(Viktor);
        list.add(Viego);
        list.add(VelKoz);
        list.add(Vayne);
        list.add(Varus);
        list.add(Udyr);
        list.add(Trundle);
        list.add(Thresh);
        list.add(Teemo);
        list.add(Taric);
        list.add(Syndra);
        list.add(Soraka);
        list.add(Sett);
        list.add(Sejuani);
        list.add(Ryze);
        list.add(Riven);
        list.add(Rell);
        list.add(Poppy);
        list.add(Pantheon);
        list.add(Nunu);
        list.add(Nautilus);
        return list;
    }
}
